# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.

# Placez ici les paramètres qui ne doivent pas changer sur chaque machine où l'application est déployée
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cover_directory: '%kernel.project_dir%/public/uploads'
    # Répertoire de stockage des images de couverture
    covers_directory: '%kernel.project_dir%/public/uploads/covers'
    uploads_directory: '%kernel.project_dir%/public/uploads/media'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    app.mailer.from_email: 'kayzeurdylan@gmail.com'
    app.mailer.from_name: 'Syncylinky'

services:
    App\Service\MessageService: ~
    App\EventListener\MessageSentListener:
        arguments:
            $messageService: '@App\Service\MessageService'
    App\Service\CommunityDescriptionService:
        arguments:
            $gemini: '@Google\GeminiPhp\Gemini'

    App\EventListener\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    App\Service\QrCodeService:
        arguments:
            $builder: '@Endroid\QrCode\Builder\Builder'
    # default configuration for services in *this* file
    _defaults:
        bind:
            $stripeSK: '%env(STRIPE_SK)%'
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés d'événements, etc.

    # rend les classes dans src/ disponibles pour être utilisées comme services
    # cela crée un service par classe dont l'id est le nom complet de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # ajoutez plus de définitions de services lorsque une configuration explicite est nécessaire
    # notez que les dernières définitions *remplacent* toujours les précédentes